services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # mongodb:
  #   image: mongo
  #   container_name: mongo
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongodb
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    volumes:
      - mailpit_data:/data
    restart: unless-stopped

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   ports:
  #     - "9000:9000" # MinIO API
  #     - "9001:9001" # MinIO console
  #   environment:
  #     MINIO_ROOT_USER: minio_admin
  #     MINIO_ROOT_PASSWORD: minio_admin
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio_data:/data

  # typesense:
  #   image: typesense/typesense:29.0
  #   container_name: typesense
  #   ports:
  #     - "8108:8108"
  #   environment:
  #     TYPESENSE_DATA_DIR: /data
  #     TYPESENSE_API_KEY: xyz123
  #     TYPESENSE_LOG_LEVEL: info
  #   volumes:
  #     - typesense_data:/data

volumes:
  postgres_data:
  redis_data:
  mailpit_data:
  # mongo_data:
  # minio_data:
  # typesense_data:
